name: PR Test

on:
  pull_request:
    branches:
      - main

jobs:
  test_lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: "**/pyproject.toml"

      - name: install uv
        uses: yezz123/setup-uv@v4
        with:
          uv-venv: "arcee-ci"

      - name: install dependencies
        run: uv pip install invoke && uv pip install .

      - name: Run inv lint
        run: inv lint

      - name: Run tests
        run: inv test
